version: "0.2"
ignorePaths:
  - .git
  - .gitignore
dictionaryDefinitions: []
dictionaries: []
words:
  - addgroup
  - adduser
  - anthropics
  - arigaio
  - bluemonday
  - Buildx
  - coverprofile
  - DB_DBNAME
  - DBTX
  - elasticmq
  - errcheck
  - getenv
  - GOARCH
  - gofmt
  - goimports
  - golangci
  - gosimple
  - govet
  - healthcheck
  - HTMX
  - ineffassign
  - isready
  - ldflags
  - misspell
  - pkgs
  - sqlc
  - sslmode
  - staticcheck
  - synctest
  - templ
  - test
  - testutil
  - tfstate
  - tfvars
  - tzdata
  - usecase
