name: 'AWS Authentication'
description: 'Configure AWS credentials via OIDC'

inputs:
  role-arn:
    description: 'AWS IAM Role ARN for OIDC authentication'
    required: true
  region:
    description: 'AWS Region'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Configure AWS credentials via OIDC
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ inputs.role-arn }}
        aws-region: ${{ inputs.region }}
