// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

type Querier interface {
	CountTasksByStatus(ctx context.Context, status string) (int64, error)
	CountTasksByUser(ctx context.Context, userID uuid.NullUUID) (int64, error)
	CreateTask(ctx context.Context, arg CreateTaskParams) (Task, error)
	DeleteTask(ctx context.Context, id uuid.UUID) error
	GetTask(ctx context.Context, id uuid.UUID) (Task, error)
	ListOverdueTasks(ctx context.Context) ([]Task, error)
	ListTasks(ctx context.Context) ([]Task, error)
	ListTasksByStatus(ctx context.Context, status string) ([]Task, error)
	ListTasksByUser(ctx context.Context, userID uuid.NullUUID) ([]Task, error)
	ListTasksByUserAndStatus(ctx context.Context, arg ListTasksByUserAndStatusParams) ([]Task, error)
	ListUpcomingTasks(ctx context.Context, dueDate sql.NullTime) ([]Task, error)
	UpdateTask(ctx context.Context, arg UpdateTaskParams) (Task, error)
	UpdateTaskStatus(ctx context.Context, arg UpdateTaskStatusParams) (Task, error)
}

var _ Querier = (*Queries)(nil)
