// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tasks.sql

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const countTasksByStatus = `-- name: CountTasksByStatus :one
SELECT COUNT(*) FROM tasks
WHERE status = $1
`

func (q *Queries) CountTasksByStatus(ctx context.Context, status string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countTasksByStatus, status)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countTasksByUser = `-- name: CountTasksByUser :one
SELECT COUNT(*) FROM tasks
WHERE user_id = $1
`

func (q *Queries) CountTasksByUser(ctx context.Context, userID uuid.NullUUID) (int64, error) {
	row := q.db.QueryRowContext(ctx, countTasksByUser, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createTask = `-- name: CreateTask :one
INSERT INTO tasks (
    title,
    description,
    status,
    priority,
    due_date,
    user_id
) VALUES (
    $1, $2, $3, $4, $5, $6
) RETURNING id, title, description, status, priority, due_date, created_at, updated_at, completed_at, user_id
`

type CreateTaskParams struct {
	Title       string         `json:"title"`
	Description sql.NullString `json:"description"`
	Status      string         `json:"status"`
	Priority    string         `json:"priority"`
	DueDate     sql.NullTime   `json:"due_date"`
	UserID      uuid.NullUUID  `json:"user_id"`
}

func (q *Queries) CreateTask(ctx context.Context, arg CreateTaskParams) (Task, error) {
	row := q.db.QueryRowContext(ctx, createTask,
		arg.Title,
		arg.Description,
		arg.Status,
		arg.Priority,
		arg.DueDate,
		arg.UserID,
	)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.Priority,
		&i.DueDate,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
		&i.UserID,
	)
	return i, err
}

const deleteTask = `-- name: DeleteTask :exec
DELETE FROM tasks
WHERE id = $1
`

func (q *Queries) DeleteTask(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteTask, id)
	return err
}

const getTask = `-- name: GetTask :one
SELECT id, title, description, status, priority, due_date, created_at, updated_at, completed_at, user_id FROM tasks
WHERE id = $1
`

func (q *Queries) GetTask(ctx context.Context, id uuid.UUID) (Task, error) {
	row := q.db.QueryRowContext(ctx, getTask, id)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.Priority,
		&i.DueDate,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
		&i.UserID,
	)
	return i, err
}

const listOverdueTasks = `-- name: ListOverdueTasks :many
SELECT id, title, description, status, priority, due_date, created_at, updated_at, completed_at, user_id FROM tasks
WHERE due_date < NOW()
  AND status NOT IN ('completed', 'cancelled')
ORDER BY due_date ASC
`

func (q *Queries) ListOverdueTasks(ctx context.Context) ([]Task, error) {
	rows, err := q.db.QueryContext(ctx, listOverdueTasks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Task
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.Status,
			&i.Priority,
			&i.DueDate,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CompletedAt,
			&i.UserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTasks = `-- name: ListTasks :many
SELECT id, title, description, status, priority, due_date, created_at, updated_at, completed_at, user_id FROM tasks
ORDER BY created_at DESC
`

func (q *Queries) ListTasks(ctx context.Context) ([]Task, error) {
	rows, err := q.db.QueryContext(ctx, listTasks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Task
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.Status,
			&i.Priority,
			&i.DueDate,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CompletedAt,
			&i.UserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTasksByStatus = `-- name: ListTasksByStatus :many
SELECT id, title, description, status, priority, due_date, created_at, updated_at, completed_at, user_id FROM tasks
WHERE status = $1
ORDER BY created_at DESC
`

func (q *Queries) ListTasksByStatus(ctx context.Context, status string) ([]Task, error) {
	rows, err := q.db.QueryContext(ctx, listTasksByStatus, status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Task
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.Status,
			&i.Priority,
			&i.DueDate,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CompletedAt,
			&i.UserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTasksByUser = `-- name: ListTasksByUser :many
SELECT id, title, description, status, priority, due_date, created_at, updated_at, completed_at, user_id FROM tasks
WHERE user_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListTasksByUser(ctx context.Context, userID uuid.NullUUID) ([]Task, error) {
	rows, err := q.db.QueryContext(ctx, listTasksByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Task
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.Status,
			&i.Priority,
			&i.DueDate,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CompletedAt,
			&i.UserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTasksByUserAndStatus = `-- name: ListTasksByUserAndStatus :many
SELECT id, title, description, status, priority, due_date, created_at, updated_at, completed_at, user_id FROM tasks
WHERE user_id = $1 AND status = $2
ORDER BY created_at DESC
`

type ListTasksByUserAndStatusParams struct {
	UserID uuid.NullUUID `json:"user_id"`
	Status string        `json:"status"`
}

func (q *Queries) ListTasksByUserAndStatus(ctx context.Context, arg ListTasksByUserAndStatusParams) ([]Task, error) {
	rows, err := q.db.QueryContext(ctx, listTasksByUserAndStatus, arg.UserID, arg.Status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Task
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.Status,
			&i.Priority,
			&i.DueDate,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CompletedAt,
			&i.UserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUpcomingTasks = `-- name: ListUpcomingTasks :many
SELECT id, title, description, status, priority, due_date, created_at, updated_at, completed_at, user_id FROM tasks
WHERE due_date BETWEEN NOW() AND $1
  AND status NOT IN ('completed', 'cancelled')
ORDER BY due_date ASC
`

func (q *Queries) ListUpcomingTasks(ctx context.Context, dueDate sql.NullTime) ([]Task, error) {
	rows, err := q.db.QueryContext(ctx, listUpcomingTasks, dueDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Task
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.Status,
			&i.Priority,
			&i.DueDate,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CompletedAt,
			&i.UserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTask = `-- name: UpdateTask :one
UPDATE tasks
SET
    title = COALESCE($2, title),
    description = COALESCE($3, description),
    status = COALESCE($4, status),
    priority = COALESCE($5, priority),
    due_date = COALESCE($6, due_date),
    updated_at = NOW()
WHERE id = $1
RETURNING id, title, description, status, priority, due_date, created_at, updated_at, completed_at, user_id
`

type UpdateTaskParams struct {
	ID          uuid.UUID      `json:"id"`
	Title       sql.NullString `json:"title"`
	Description sql.NullString `json:"description"`
	Status      sql.NullString `json:"status"`
	Priority    sql.NullString `json:"priority"`
	DueDate     sql.NullTime   `json:"due_date"`
}

func (q *Queries) UpdateTask(ctx context.Context, arg UpdateTaskParams) (Task, error) {
	row := q.db.QueryRowContext(ctx, updateTask,
		arg.ID,
		arg.Title,
		arg.Description,
		arg.Status,
		arg.Priority,
		arg.DueDate,
	)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.Priority,
		&i.DueDate,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
		&i.UserID,
	)
	return i, err
}

const updateTaskStatus = `-- name: UpdateTaskStatus :one
UPDATE tasks
SET
    status = $2,
    completed_at = CASE WHEN $2 = 'completed' THEN NOW() ELSE NULL END,
    updated_at = NOW()
WHERE id = $1
RETURNING id, title, description, status, priority, due_date, created_at, updated_at, completed_at, user_id
`

type UpdateTaskStatusParams struct {
	ID     uuid.UUID `json:"id"`
	Status string    `json:"status"`
}

func (q *Queries) UpdateTaskStatus(ctx context.Context, arg UpdateTaskStatusParams) (Task, error) {
	row := q.db.QueryRowContext(ctx, updateTaskStatus, arg.ID, arg.Status)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.Priority,
		&i.DueDate,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
		&i.UserID,
	)
	return i, err
}
